export default class Positions {
    static BACKPACK = 'BACKPACK'
    static CHEST = 'CHEST'

    static PAPERDOLL_HEAD = 'PAPERDOLL_HEAD'
    static PAPERDOLL_TORSO = 'PAPERDOLL_TORSO'
    static PAPERDOLL_LEGS = 'PAPERDOLL_LEGS'
    static PAPERDOLL_HAND_LEFT = 'PAPERDOLL_HAND_LEFT'
    static PAPERDOLL_HAND_RIGHT = 'PAPERDOLL_HAND_RIGHT'
    static PAPERDOLL_BACK = 'PAPERDOLL_BACK'
    static PAPERDOLL_WAIST = 'PAPERDOLL_WAIST'

    static PAPERDOLL_FOOD = 'PAPERDOLL_FOOD'
    static PAPERDOLL_POTION = 'PAPERDOLL_POTION'

    static VENDOR_EQUIPMENT = 'VENDOR_EQUIPMENT'
    static VENDOR_RESOURCES = 'VENDOR_RESOURCES'
}