export default class Positions {
    static BACKPACK = 'BACKPACK'
    static CHEST = 'CHEST'

    static PAPERDOLL_HEAD = 'PAPERDOLL_HEAD'
    static PAPERDOLL_TORSO = 'PAPERDOLL_TORSO'
    static PAPERDOLL_LEGS = 'PAPERDOLL_LEGS'
    static PAPERDOLL_HAND_LEFT = 'PAPERDOLL_HAND_LEFT'
    static PAPERDOLL_HAND_RIGHT = 'PAPERDOLL_HAND_RIGHT'
    static PAPERDOLL_BACK = 'PAPERDOLL_BACK'
    static PAPERDOLL_WAIST = 'PAPERDOLL_WAIST'

    static PAPERDOLL_FOOD = 'PAPERDOLL_FOOD'
    static PAPERDOLL_POTION = 'PAPERDOLL_POTION'

    static VENDOR_EQUIPABLES_HEAD = 'VENDOR_EQUIPABLES_HEAD'
    static VENDOR_EQUIPABLES_TORSO = 'VENDOR_EQUIPABLES_TORSO'
    static VENDOR_EQUIPABLES_LEGS = 'VENDOR_EQUIPABLES_LEGS'
    static VENDOR_EQUIPABLES_HAND_LEFT = 'VENDOR_EQUIPABLES_HAND_LEFT'
    static VENDOR_EQUIPABLES_HAND_RIGHT = 'VENDOR_EQUIPABLES_HAND_RIGHT'
    static VENDOR_EQUIPABLES_BACK = 'VENDOR_EQUIPABLES_BACK'
    static VENDOR_EQUIPABLES_WAIST = 'VENDOR_EQUIPABLES_WAIST'
    static VENDOR_CONSUMABLES_FOOD = 'VENDOR_CONSUMABLES_FOOD'
    static VENDOR_CONSUMABLES_POTION = 'VENDOR_CONSUMABLES_POTION'

}